name: MultiMarriage
version: 1.0b
main: rabbit.multimarry.Marriage
author: rabbit
description: A plugin wich provides the function to start relationships in minecraft.
dev-url: http://localhost:8080/
softdepend: [Vault]
commands:
  marry:
    description: Marriage main command.
    usage: /marry <args>
permissions:
  marry.*:
    description: Allows all Marriage Commands
    children:
      marry.admin:
        description: Allows all admin commands
        children:
          marry.reload:
            description: Allows to reload the config files
          marry.multiple:
            description: Allows player to marry with multiple persons.
      marry.default:
        description: Allows default player commands
        children:
          marry.divorce:
            description: divorce with anyone
            children:
              marry.divorce.*:
                description: divorce with anyone
          marry.marry:
            description: Allows to marry with players
          marry.master:
            description: Allows to set a partner to master
          marry.tp:
            description: Allows to tp to your partner
          marry.home:
            description: Allows to tp to your home if set
          marry.sethome:
            description: Allwos to set your Marriage home
          marry.gift:
            description: Allows to gift item to your partner
          marry.chat:
            description: Allows to chat with your partner
          marry.seen:
            description: Allows to see your last login from your partner